Update swift.yml

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -32,7 +32,7 @@ jobs:
         macos: ['macos-14']
         scheme: ['DocumentationBuilder']
         command: ['docbuild']
-        platform: ['macOS']
+        platform: ['macOS', 'iOS', 'tvOS', 'watchOS']
     steps:
       - name: Switch xcode to ${{ matrix.xcode }}
         uses: maxim-lobanov/setup-xcode@v1.5.1
@@ -52,23 +52,32 @@ jobs:
         run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
       - name: Skip Macro Validation
         run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
+      - name: Generate DocC Documentation
+        id: generate_docs
+        run: |
+          xcodebuild docbuild -scheme DocumentationBuilder -destination generic/platform=${{ matrix.platform }} -derivedDataPath ./build
+          doccarchive_path=$(find ./build -name '*.doccarchive' -print -quit)
+          if [ -z "$doccarchive_path" ]; then
+            echo "No .doccarchive file found."
+            exit 1
+          fi
+          echo "::set-output name=doccarchive_path::$doccarchive_path"
       - name: Convert DocC Archive to Static Website
-        uses: fwcd/swift-docc-action@v1
-        with:
-          target: DocumentationBuilder
-          output: ./docs
-          hosting-base-path: ''
-          disable-indexing: 'true'
-          transform-for-static-hosting: 'true'
+        run: |
+          docc_path=$(xcrun --find docc)
+          if [ -z "$docc_path" ]; then
+            echo "docc command not found."
+            exit 1
+          fi
+          ${docc_path} process-archive transform-for-static-hosting ${{ steps.generate_docs.outputs.doccarchive_path }} \
+          --output-path ./docs \
+          --hosting-base-path /DocumentationBuilder
       - name: Setup Pages
         uses: actions/configure-pages@v5
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: './docs'
-          base-url: ""  # Ensure this matches your GitHub Pages URL structure
-      - name: Create .nojekyll file
-        run: touch ./docs/.nojekyll
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
